### ISSUE TITLE
2 ASCII error's and "from" Syntax Error

### ISSUE THREAD

**Issue by colelamers** [masasin/resume#13]
Below are the separate times I tried running this in Powershell on Windows 10. I have everything installed and was able to install requirements through pip. Not really sure where to go from here. The README was kinda vague so I apologize that I'm lost.

```
PS B:\downloads\resume-master> python generate.py
  File "generate.py", line 3
SyntaxError: Non-ASCII character '\xc3' in file generate.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

PS B:\downloads\resume-master> python generate.py
  File "generate.py", line 3
SyntaxError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

PS B:\downloads\resume-master> python generate.py
Traceback (most recent call last):
  File "generate.py", line 14, in <module>
    from resume_generator import environment_setup, ResumeGenerator
  File "B:\downloads\resume-master\resume_generator.py", line 65
    yield from glob.iglob("{}/*{}".format(directory, ext))
             ^
SyntaxError: invalid syntax
```

**Comment by masasin** [comment]
Hi! Which version of Python are you using? It doesn't work with Python 2. You can verify with `python --version`. Maybe you need `python3` instead?

If that doesn't work, try using the Git Bash shell.

**Comment by colelamers** [comment]
Alright so I gave up trying in Windows and jumped to linux. So the ASCII issue was because of Python 2.*. However I'm encountering new issues. I have everything installed as well. Here is what I got now:

```
mas@Mas:~/resume-master$ py --version
Pythonpy ???
Python 3.6.9
mas@Mas:~/resume-master$ py resume_generator.py
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    resume_generator.py
NameError: name 'resume_generator' is not defined

```
As well as:

```
mas@Mas:~/resume-master$ py resume_generator.py
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    resume_generator.py
NameError: name 'resume_generator' is not defined
mas@Mas:~/resume-master$ py generate.py
Traceback (most recent call last):
  File "/usr/bin/py", line 167, in <module>
    result = eval(args.expression)
  File "<string>", line 1, in <module>
    generate.py
NameError: name 'generate' is not defined
mas@Mas:~/resume-master$
```
