### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by crudlover** [masasin/resume#14]
Got this error when running generate.py on Mint Linux:

```
python generate.py
/home/mint/Desktop/resume-master/resume_generator.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(file)
latex:  43%|█████████████▋                  | 3/7 [00:00<00:00, 57.79sections/s]
Rendering résumé:   0%|                              | 0/1 [00:00<?, ?formats/s]
Traceback (most recent call last):
  File "generate.py", line 62, in <module>
    sys.exit(main())
  File "generate.py", line 58, in main
    ResumeGenerator().run(context_names=args.contexts,
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 149, in run
    self.generate_resumes(context_map.values())
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 206, in generate_resumes
    self.process_resume(context)
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 191, in process_resume
    rendered_resume = context.render_resume(self.data)
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 557, in render_resume
    body += self._render_section(section, data).rstrip() + "\n\n\n"
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 487, in _render_section
    rendered_section = self.render_template(section_template_name,
  File "/home/mint/Desktop/resume-master/resume_generator.py", line 446, in render_template
    return self.jinja_env.get_template(template_name + self.filetype)\
  File "/home/mint/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/mint/.local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "templates/latex/sections/items.tex", line 24, in top-level template code
    \cvlistitem{<< item >>}
  File "templates/latex/section.tex", line 3, in top-level template code
    ~< block body >~
  File "templates/latex/sections/items.tex", line 37, in block 'body'
    ~< for item in items >~
TypeError: 'NoneType' object is not iterable
```

Any idea what is going on here? Thank you.

**Comment by masasin** [comment]
Hi! The YAML loader doesn't have its version pinned in the requirements, and the latest YAML needs a loader to be specified because the previous version allowed arbitrary code execution. It should work now.
